# Generated by Django 5.2.8 on 2026-03-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0002_alter_menuitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
